services:
  llamanexus:
    container_name: llamanexus
    image: makershop/llamanexus:beta
    pull_policy: always
    tty: true
    ports:
      - "50052:50052"
    command: worker -v
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
